cc_test(
    name = "simple_nlp",
    size = "small",
    srcs = ["simple_nlp.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//sip",
    ],
)

cc_test(
    name = "simple_qp",
    size = "small",
    srcs = ["simple_qp.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//sip",
    ],
)
